# -*- coding: utf-8 -*-
"""practiceNumpyFifty.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1duFniXlEhzwp4uQ1EtnHlZtLWR2waAWW

# **NUMPY**

# **November 06, 2025 Donnerstag 00:18**

***These 50 problems cover almost every NumPy concept needed for data analytics, data science, and interviews:***

**Easy**: Basics, creation, simple operations

**Medium**: Indexing, slicing, stacking, statistics

**Hard**: Linear algebra, broadcasting, advanced operations

**Hardest**: Real-world datasets, probability, distance metrics, normalization

# **EASY (1–15) – Basics of NumPy**

***Note: I will import numpy for each task so don't think akward or something else why i am using mulitiple time***

**1.	Create a 1D array of numbers from 0 to 9.**
"""

import numpy as np
npArray = np.arange(10)
print(f"Numpy Array: {npArray}")
print(f"Numpy Array Dimension: {npArray.ndim}")

"""**2. Create a 3×3 matrix filled with zeros.**"""

import numpy as np
npZeros = np.zeros((3,3))
print(f"Numpy Zeros Array: \n {npZeros}")
print(f"Numpy Zeros Array Dimension: {npZeros.shape}")

"""**3.	Create a 2×3 matrix filled with ones.**"""

import numpy as np
npOnes = np.ones((2,3))
print(f"Numpy Ones Array: \n {npOnes}")
print(f"Numpy Ones Array Dimension: {npOnes.shape}")

"""**4.	Generate an array of 10 random numbers between 0 and 1.**"""

import numpy as np
rand = np.random.rand(10)
print(f"Random Between 0 to 1: \n {rand}")

"""**5.	Create a 1D array of numbers from 10 to 50 with a step of 5.**"""

import numpy as np
npStepJump = np.arange(10,50,5)
print(f"Number From 10 to 50 with the Jump of 5: \n {npStepJump}")

"""**6.	Find the shape, size, and data type of a given array.**"""

givenArray = [1,23,12,14,15,16,16,17]
npArr = np.array(givenArray)
print(f"Shape: {npArr.shape}")
print(f"Size: {npArr.size}")
print(f"DataType: {npArr.dtype}")

"""**7.	Convert a Python list [1,2,3,4] into a NumPy array.**"""

import numpy as np
myList = [1,2,3,4,5]
npArrays = np.array(myList)
print(f"Numpy Array: \n{npArrays}")
print(f"Data Type: {type(npArrays)}")

"""**8.	Reshape a 1D array of 12 elements into a 3×4 array.**"""

import numpy as np
zwölfElement = np.arange(12)
print(f"1D Array: \n{zwölfElement}")
print(f"3x4 Converted Array: \n{zwölfElement.reshape(3,4)}")

"""**9.	Create a 5×5 identity matrix.**"""

import numpy as np
identityMatrix = np.identity(5)
print(identityMatrix)

"""**10.	Create an array of 10 equally spaced numbers between 0 and 1.**"""

import numpy as np

equalSpace = np.linspace(0,1,10)
print(f"Eqaul Space 0 to 1: \n{equalSpace}")

