# -*- coding: utf-8 -*-
"""practiceNumpyFifty.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1duFniXlEhzwp4uQ1EtnHlZtLWR2waAWW

# **NUMPY**

# **November 06, 2025 Donnerstag 00:18**

***These 50 problems cover almost every NumPy concept needed for data analytics, data science, and interviews:***

**Easy**: Basics, creation, simple operations

**Medium**: Indexing, slicing, stacking, statistics

**Hard**: Linear algebra, broadcasting, advanced operations

**Hardest**: Real-world datasets, probability, distance metrics, normalization

# **EASY (1–15) – Basics of NumPy**

***Note: I will import numpy for each task so don't think akward or something else why i am using mulitiple time***

**1.	Create a 1D array of numbers from 0 to 9.**
"""

import numpy as np
npArray = np.arange(10)
print(f"Numpy Array: {npArray}")
print(f"Numpy Array Dimension: {npArray.ndim}")

"""**2. Create a 3×3 matrix filled with zeros.**"""

import numpy as np
npZeros = np.zeros((3,3))
print(f"Numpy Zeros Array: \n {npZeros}")
print(f"Numpy Zeros Array Dimension: {npZeros.shape}")

"""**3.	Create a 2×3 matrix filled with ones.**"""

import numpy as np
npOnes = np.ones((2,3))
print(f"Numpy Ones Array: \n {npOnes}")
print(f"Numpy Ones Array Dimension: {npOnes.shape}")

"""**4.	Generate an array of 10 random numbers between 0 and 1.**"""

import numpy as np
rand = np.random.rand(10)
print(f"Random Between 0 to 1: \n {rand}")

"""**5.	Create a 1D array of numbers from 10 to 50 with a step of 5.**"""

import numpy as np
npStepJump = np.arange(10,50,5)
print(f"Number From 10 to 50 with the Jump of 5: \n {npStepJump}")

"""**6.	Find the shape, size, and data type of a given array.**"""

givenArray = [1,23,12,14,15,16,16,17]
npArr = np.array(givenArray)
print(f"Shape: {npArr.shape}")
print(f"Size: {npArr.size}")
print(f"DataType: {npArr.dtype}")

"""**7.	Convert a Python list [1,2,3,4] into a NumPy array.**"""

import numpy as np
myList = [1,2,3,4,5]
npArrays = np.array(myList)
print(f"Numpy Array: \n{npArrays}")
print(f"Data Type: {type(npArrays)}")

"""**8.	Reshape a 1D array of 12 elements into a 3×4 array.**"""

import numpy as np
zwölfElement = np.arange(12)
print(f"1D Array: \n{zwölfElement}")
print(f"3x4 Converted Array: \n{zwölfElement.reshape(3,4)}")

"""**9.	Create a 5×5 identity matrix.**"""

import numpy as np
identityMatrix = np.identity(5)
print(identityMatrix)

"""**10.	Create an array of 10 equally spaced numbers between 0 and 1.**"""

import numpy as np

equalSpace = np.linspace(0,1,10)
print(f"Eqaul Space 0 to 1: \n{equalSpace}")

"""**11.	Extract the first 3 rows of a 5×5 random matrix.**"""

import numpy as np
randArr = np.round(np.random.rand(5,5)*100)
print(f"Random Array Of 5x5: \n{randArr}")
print(f"First 3 Row: \n{randArr[:3]}")

"""**12.	Replace all negative numbers in an array with zero.**"""

import numpy as np
listing = [1,2,4,5,6,78,-9,-3,34]
npList = np.array(listing)
print(f"Original Array: \n{npList}")
npList[npList < 0] = 0
print(f"After Mask: \n{npList}")

"""**13.	Multiply two arrays element-wise.**"""

import numpy as np
listing1 = [1,2,4,45,26,78,9,34]
listing2 = [1,2,4,63,18,19,113,3]
npList1 = np.array(listing1)
npList2 = np.array(listing2)
print(f"Original List1: \n{npList1}")
print(f"Original List2: \n{npList2}")

print("x----------------------------------x")

#Approach # 01 - With * sign
multApproach1 = npList1 * npList2
#Approach # 02 - With multiply funciton
multApproach2 = np.multiply(npList1,npList2)

print(f"Approach # 01: \n{multApproach1}")
print(f"Approach # 02: \n{multApproach2}")

"""**14.	Find the sum, mean, and standard deviation of a 1D array.**"""

import numpy as np
oneDimArray = [1,2,3,5,6,71,123,13,13,2,3,32,21,34]
npOneDim = np.array(oneDimArray)
print(f"Original Array:\n{npOneDim}")
print(f"Sum: {np.sum(npOneDim)}")
print(f"Mean: {np.mean(npOneDim)}")
print(f"Median: {np.median(npOneDim)}")
print(f"Min: {np.min(npOneDim)}")
print(f"Max: {np.max(npOneDim)}")
print(f"Standard Deviation: {np.std(npOneDim)}")

"""**15.	Flatten a 2D array into a 1D array.**"""

import numpy as np
twoDim = [
    [1,2,4,5,67,77,1],
    [1,2,4,5,67,77,1],
]
npTwoDim = np.array(twoDim)
print(f"Original Array:\n {npTwoDim}")
print(f"Flatten Array:\n {npTwoDim.flatten()}")

"""# **MEDIUM (16–30) – Indexing, slicing, statistics, and operations**

**16.	Create a 10×10 array and find the minimum and maximum values.**
"""

import numpy as np


npArr = np.random.random((10,10))
npArrMin = npArr.min()
npArrMax = npArr.max()
print(f"Random 10x10 array: \n{npArr}")
print(f"Shape: {npArr.shape}")
print(f"Min: {npArrMin}")
print(f"Max: {npArrMax}")
print(f"Flatten: {npArr.flatten()}")
print(f"Index Of Max: {npArr.flatten().argmax()}")

"""**17.	Select all odd numbers from a 1D array of 1–20.**"""

import numpy as np
import random
num = np.random.randint(1, 20, size=20)  # 1 to 20
odd = num[num%2 !=0]
print(f"Original: {num}")
print(f"Odd: {odd}")

"""**18.	Reverse a 1D array.**"""

import numpy as np
import random
oneDimNp= np.random.randint(1, 20, size=10)  # 1 to 10
print(f"Original: {oneDimNp}")
# Approach 1:
reversed = np.flip(oneDimNp)
print(f"Approach 1 - Reversed: {reversed}")
# Approach 2:
rev = oneDimNp[::-1]
print(f"Approach 2 - Reversed: {rev}")

"""**19.	Extract a submatrix (2×2) from a 4×4 matrix.**"""

import numpy as np
npOriginal = np.arange(16).reshape(4,4)
print(f"Original: \n{npOriginal}")
print(f"Original Matrix Shape: {npOriginal.shape}")
subMatrix = npOriginal[0:2,0:2]
print(f"SubMatrix: \n{subMatrix}")
print(f"Sub Matrix Shape: {subMatrix.shape}")

"""**20.	Stack two arrays vertically and horizontally.**"""

import numpy as np
numpyArr = np.arange(16).reshape(4,4)
numpyArr2 = np.arange(16,32).reshape(4,4)
print(f"Array1: \n{numpyArr}")
print(f"Array2: \n{numpyArr2}")
horizStack = np.hstack([numpyArr, numpyArr2])
print(f"Horizontal Stack: \n{horizStack}")
verStack = np.vstack([numpyArr, numpyArr2])
print(f"Vertical Stack: \n{verStack}")

"""**21.	Create a 1D array of 15 random integers from 0 to 100 and sort it.**"""

import numpy as np
rand = np.random.randint(0,100, size=15)
print(f"Original: {rand}")
print(f"Sorted: {np.sort(rand)}")

"""**22.	Compute the dot product of two 2×2 matrices.**"""

import numpy as np
arr1 = np.arange(1,8,2).reshape(2,2)
arr2 = np.arange(1,5).reshape(2,2)

print(f"matrix 1: \n{arr1}")
print(f"matrix 2: \n{arr2}")
print(f"Dot Product: \n{np.dot(arr1,arr2)}")

"""**23.	Find the unique elements and their counts in an array.**"""

import numpy as np

arr = np.array([[1, 2, 2],
                [3, 5, 1],
                [4, 2, 1]])
# Get unique elements and their counts
unique_vals, counts = np.unique(arr, return_counts=True)
print(unique_vals)
print(counts)

"""**24.	Normalize a 1D array to have values between 0 and 1.**"""

import numpy as np

arr = np.array([100, 20, 30, 410, 501])

# Min-max normalization
normalized = (arr - arr.min()) / (arr.max() - arr.min())

print("Original array:", arr)
print("Normalized array:", normalized)

# Z-score normalization
mean = arr.mean()
std = arr.std()

standard_normalized = (arr - mean) / std

print("Original array:", arr)
print("Mean:", mean)
print("Std Dev:", std)
print("Z-score Normalized:", standard_normalized)

"""***Extra: Normalization for 2D Array:***"""

import numpy as np
arr = np.array([
    [10, 20, 30],
    [5, 15, 40],
    [25, 35, 45]
])

min = arr.min()
max = arr.max()
print(arr)
print(f"Min: {min} & Max: {max}")

nor = (arr-min) / (max-min)
print(nor)

rowMin = arr.min(axis=1, keepdims=True)
rowMax = arr.max(axis=1, keepdims=True)

print(f"Row Min: {rowMin} & Row Max: {rowMax}")

rowNor = (arr-rowMin) / (rowMax-rowMin)
print(f"Row Wise Normalization: {rowNor}")
#same with col but axis = 0

"""**25.	Compute the cumulative sum of a 1D array.**"""

import numpy as np
arr = np.random.randint(1,10, size=4)
print(f"Original: {arr}")
print(f"Comulative Sum: {np.cumsum(arr)}")

"""***Extra: by manual python:***"""

import random
import numpy as np
arr = [1,3,4,6,6,10,20,5,5,4,3,2,1]
def myCumSum(yourArr):
  arr = np.array(yourArr)
  cumsum =  []
  sum = 0
  for i in range(len(arr)):
    if i == 0:
      sum = arr[i]
      cumsum.append(arr[i])
    else:
      sum = sum + arr[i]
      cumsum.append(sum)
  return np.array(cumsum)

myCumSum(arr)

"""**26.	Create a boolean mask to select elements greater than 5 from an array.**"""

import numpy as np
arr = np.random.randint(1,10, size=10)
print(f"Original: {arr}")
maskArr = arr>5
filterArr = arr[maskArr]
print(f"Boolen Mask Greater than 5: {maskArr}")
print(f"Filtered: {filterArr}")

"""***Extra: Boolean Masking of Rows and Columns***"""

import numpy as np

arr = np.random.randint(1, 7, size=(4, 4))
print(f"Original: \n{arr}")
maskRow = (arr>5).any(axis=1)

print("x-----------------x")

#for rows:
print(f"Mask Row: {maskRow}")
filterRow = arr[maskRow,:]
print(f"Filter Row: \n{filterRow}")

print("x-----------------x")

#for columns:
maskCol = (arr>5).any(axis=0)
print(f"Mask Columns: {maskCol}")
filterCol = arr[:,maskCol]
print(f"Filter Columns: \n{filterCol}")

"""**27.	Replace all odd numbers in an array with -1.**"""

import numpy as np
npArr = np.arange(1,11)
print(f"Original: {npArr}")
npArr[npArr%2==0] = -1
print(f"Odd Replaced: {npArr}")

"""**28.	Compute row-wise and column-wise sum of a 3×4 matrix.**"""

import numpy as np
npArr2 = np.random.randint(1,5, size=(3,4))
print(f"Original: \n{npArr2}")

print("x-------------x")

rowSum = np.sum(npArr2,axis=1)
print(f"Row Sum: {rowSum}")

print("x-------------x")
colSum = np.sum(npArr2,axis=0)
print(f"Columns Sum: {colSum}")

"""**29.	Create a 3×3 matrix and compute its transpose.**"""

import numpy as np
# print(np.zeros((3,3), dtype=np.int32))
npArr3 = np.random.randint(1,19, size=(3,3))
print(f"Original:\n{npArr3}")
print("x--------------x")
transpose = np.transpose(npArr3)
print(f"Transpose: \n{transpose}")

"""**30.	Perform element-wise square and square-root operations on an array.**"""

import numpy as np
npArr1D = np.arange(2,7)
print(f"1D Array Original: {npArr1D}")
sq1D = np.square(npArr1D)
print(f"Square of 1D: {sq1D}")
sqrt1D = np.sqrt(npArr1D)
print(f"Square Root of 1D: \n{sqrt1D}")
print("x---------------------x")

npArr2D = np.random.randint(1,7, size=(2,2))
print(f"2D Array Original: \n{npArr2D}")
sq2D = np.square(npArr2D)
print(f"Square of 2D: \n{sq2D}")
sqrt2D = np.sqrt(npArr2D)
print(f"Square Root of 2D: \n{sqrt2D}")

